from copy import copy

from mwcleric.fandom_client import FandomClient
from mwcleric.auth_credentials import AuthCredentials
from mwcleric.page_modifier import PageModifierBase
from mwparserfromhell.nodes import Tag, Template

credentials = AuthCredentials(user_file="me")
site = FandomClient('subnautica-belowzero', credentials=credentials)
summary = 'Updating wiki for incoming merger'

pages = {
    "Advanced Wiring Kit": "Advanced Wiring Kit (Below Zero)",
    "Aerogel": "Aerogel (Below Zero)",
    "Air Bladder": "Air Bladder (Below Zero)",
    "Alien Containment": "Alien Containment (Below Zero)",
    "Alien Statue": "Alien Statue (Below Zero)",
    "Aquarium": "Aquarium (Below Zero)",
    "Bar Table": "Bar Table (Below Zero)",
    "Basic Materials": "Basic Materials (Below Zero)",
    "Battery": "Battery (Below Zero)",
    "Battery Charger": "Battery Charger (Below Zero)",
    "Beacon": "Beacon (Below Zero)",
    "Beds": "Beds (Below Zero)",
    "Bench": "Bench (Below Zero)",
    "Benzene": "Benzene (Below Zero)",
    "Bioreactor": "Bioreactor (Below Zero)",
    "Bladderfish": "Bladderfish (Below Zero)",
    "Blue Barnacles": "Blue Barnacles (Below Zero)",
    "Boomerang": "Boomerang (Below Zero)",
    "Bulkhead": "Bulkhead (Below Zero)",
    "Camera Drone": "Camera Drone (Below Zero)",
    "Chairs": "Chairs (Below Zero)",
    "Chinese Potato": "Chinese Potato (Below Zero)",
    "Chinese Potato Plant": "Chinese Potato Plant (Below Zero)",
    "Coffee Vending Machine": "Coffee Vending Machine (Below Zero)",
    "Compass": "Compass (Below Zero)",
    "Computer Chip": "Computer Chip (Below Zero)",
    "Copper Ore": "Copper Ore (Below Zero)",
    "Copper Wire": "Copper Wire (Below Zero)",
    "Counter": "Counter (Below Zero)",
    "Crashfish": "Crashfish (Below Zero)",
    "Creepvine": "Creepvine (Below Zero)",
    "Creepvine Sample": "Creepvine Sample (Below Zero)",
    "Creepvine Seed Cluster": "Creepvine Seed Cluster (Below Zero)",
    "Crystalline Sulfur": "Crystalline Sulfur (Below Zero)",
    "Databank": "Databank (Below Zero)",
    "Desk": "Desk (Below Zero)",
    "Dialogue": "Dialogue (Below Zero)",
    "Diamond": "Diamond (Below Zero)",
    "Disinfected Water": "Disinfected Water (Below Zero)",
    "Earthen Coral Tubes": "Earthen Coral Tubes (Below Zero)",
    "Enameled Glass": "Enameled Glass (Below Zero)",
    "Exterior Growbed": "Exterior Growbed (Below Zero)",
    "Fabricator": "Fabricator (Below Zero)",
    "Fiber Mesh": "Fiber Mesh (Below Zero)",
    "Filtered Water": "Filtered Water (Below Zero)",
    "Fins": "Fins (Below Zero)",
    "Fins (Disambiguation)": "Fins (Disambiguation) (Below Zero)",
    "First Aid Kit": "First Aid Kit (Below Zero)",
    "Flare": "Flare (Below Zero)",
    "Flashlight": "Flashlight (Below Zero)",
    "Floodlight": "Floodlight (Below Zero)",
    "Flora": "Flora (Below Zero)",
    "Foundation": "Foundation (Below Zero)",
    "Gas Torpedo": "Gas Torpedo (Below Zero)",
    "Gel Sack": "Gel Sack (Below Zero)",
    "Glass": "Glass (Below Zero)",
    "Gold": "Gold (Below Zero)",
    "Grav Trap": "Grav Trap (Below Zero)",
    "Grub Basket": "Grub Basket (Below Zero)",
    "Habitat Builder": "Habitat Builder (Below Zero)",
    "Hatch": "Hatch (Below Zero)",
    "High Capacity O₂ Tank": "High Capacity O₂ Tank (Below Zero)",
    "Hoopfish": "Hoopfish (Below Zero)",
    "Hydrochloric Acid": "Hydrochloric Acid (Below Zero)",
    "I Compartment": "I Compartment (Below Zero)",
    "Ion Battery": "Ion Battery (Below Zero)",
    "Ion Cube": "Ion Cube (Below Zero)",
    "Ion Power Cell": "Ion Power Cell (Below Zero)",
    "Jordi's Tung": "Jordi's Tung (Below Zero)",
    "Kyanite": "Kyanite (Below Zero)",
    "L Compartment": "L Compartment (Below Zero)",
    "L Glass Compartment": "L Glass Compartment (Below Zero)",
    "Lab Container": "Lab Container (Below Zero)",
    "Ladder": "Ladder (Below Zero)",
    "Lantern Fruit": "Lantern Fruit (Below Zero)",
    "Lantern Tree": "Lantern Tree (Below Zero)",
    "Large Filtered Water": "Large Filtered Water (Below Zero)",
    "Large Resource Deposits": "Large Resource Deposits (Below Zero)",
    "Laser Cutter": "Laser Cutter (Below Zero)",
    "Lead": "Lead (Below Zero)",
    "Light Stick": "Light Stick (Below Zero)",
    "Limestone Outcrop": "Limestone Outcrop (Below Zero)",
    "Lithium": "Lithium (Below Zero)",
    "Locker": "Locker (Below Zero)",
    "Lubricant": "Lubricant (Below Zero)",
    "Magnetite": "Magnetite (Below Zero)",
    "Marblemelon": "Marblemelon (Below Zero)",
    "Marblemelon Plant": "Marblemelon Plant (Below Zero)",
    "Metal Salvage": "Metal Salvage (Below Zero)",
    "Mobile Vehicle Bay": "Mobile Vehicle Bay (Below Zero)",
    "Modification Station": "Modification Station (Below Zero)",
    "Moonpool": "Moonpool (Below Zero)",
    "Multipurpose Room": "Multipurpose Room (Below Zero)",
    "Nickel Ore": "Nickel Ore (Below Zero)",
    "Nuclear Reactor": "Nuclear Reactor (Below Zero)",
    "Nuclear Waste Disposal": "Nuclear Waste Disposal (Below Zero)",
    "Nutrient Block": "Nutrient Block (Below Zero)",
    "Observatory": "Observatory (Below Zero)",
    "Pathfinder Tool": "Pathfinder Tool (Below Zero)",
    "Picture Frame": "Picture Frame (Below Zero)",
    "Pipes": "Pipes (Below Zero)",
    "Plant Pots": "Plant Pots (Below Zero)",
    "Plant Shelf": "Plant Shelf (Below Zero)",
    "Plasteel Ingot": "Plasteel Ingot (Below Zero)",
    "Polyaniline": "Polyaniline (Below Zero)",
    "Power Cell": "Power Cell (Below Zero)",
    "Power Cell Charger": "Power Cell Charger (Below Zero)",
    "Power Transmitter": "Power Transmitter (Below Zero)",
    "Prawn Suit": "Prawn Suit (Below Zero)",
    "Prawn Suit Depth Module MK1": "Prawn Suit Depth Module MK1 (Below Zero)",
    "Prawn Suit Depth Module MK2": "Prawn Suit Depth Module MK2 (Below Zero)",
    "Prawn Suit Drill Arm": "Prawn Suit Drill Arm (Below Zero)",
    "Prawn Suit Grappling Arm": "Prawn Suit Grappling Arm (Below Zero)",
    "Prawn Suit Jump Jet Upgrade": "Prawn Suit Jump Jet Upgrade (Below Zero)",
    "Prawn Suit Propulsion Cannon": "Prawn Suit Propulsion Cannon (Below Zero)",
    "Prawn Suit Thermal Reactor": "Prawn Suit Thermal Reactor (Below Zero)",
    "Prawn Suit Torpedo Arm": "Prawn Suit Torpedo Arm (Below Zero)",
    "Propulsion Cannon": "Propulsion Cannon (Below Zero)",
    "Quartz": "Quartz (Below Zero)",
    "Reactor Rod": "Reactor Rod (Below Zero)",
    "Rebreather": "Rebreather (Below Zero)",
    "Reclaimed Water": "Reclaimed Water (Below Zero)",
    "Redwort": "Redwort (Below Zero)",
    "Reinforced Dive Suit": "Reinforced Dive Suit (Below Zero)",
    "Reinforcement": "Reinforcement (Below Zero)",
    "Repair Tool": "Repair Tool (Below Zero)",
    "Rockgrub": "Rockgrub (Below Zero)",
    "Ruby": "Ruby (Below Zero)",
    "Salt Deposit": "Salt Deposit (Below Zero)",
    "Scanner": "Scanner (Below Zero)",
    "Scanner Room": "Scanner Room (Below Zero)",
    "Scanner Room HUD Chip": "Scanner Room HUD Chip (Below Zero)",
    "Scanner Room Range Upgrade": "Scanner Room Range Upgrade (Below Zero)",
    "Scanner Room Speed Upgrade": "Scanner Room Speed Upgrade (Below Zero)",
    "Seaglide": "Seaglide (Below Zero)",
    "Shoal of Fish": "Shoal of Fish (Below Zero)",
    "Sign": "Sign (Below Zero)",
    "Silicone Rubber": "Silicone Rubber (Below Zero)",
    "Silver Ore": "Silver Ore (Below Zero)",
    "Single Wall Shelf": "Single Wall Shelf (Below Zero)",
    "Skyray": "Skyray (Below Zero)",
    "Snacks": "Snacks (Below Zero)",
    "Solar Panel": "Solar Panel (Below Zero)",
    "Speckled Rattler": "Speckled Rattler (Below Zero)",
    "Spinefish": "Spinefish (Below Zero)",
    "Spotted Dockleaf": "Spotted Dockleaf (Below Zero)",
    "Standard O₂ Tank": "Standard O₂ Tank (Below Zero)",
    "Stillsuit": "Stillsuit (Below Zero)",
    "Storage Module": "Storage Module (Below Zero)",
    "Sulfur Plant": "Sulfur Plant (Below Zero)",
    "Supply Crate": "Supply Crate (Below Zero)",
    "Survival Knife": "Survival Knife (Below Zero)",
    "Swim Charge Fins": "Swim Charge Fins (Below Zero)",
    "Synthetic Fibers": "Synthetic Fibers (Below Zero)",
    "T Compartment": "T Compartment (Below Zero)",
    "Table Coral": "Table Coral (Below Zero)",
    "Table Coral Sample": "Table Coral Sample (Below Zero)",
    "Thermal Plant": "Thermal Plant (Below Zero)",
    "Thermoblade": "Thermoblade (Below Zero)",
    "Titanium": "Titanium (Below Zero)",
    "Titanium Ingot": "Titanium Ingot (Below Zero)",
    "Trash Can": "Trash Can (Below Zero)",
    "Ultra High Capacity Tank": "Ultra High Capacity Tank (Below Zero)",
    "Update History": "Update History (Below Zero)",
    "Uraninite Crystal": "Uraninite Crystal (Below Zero)",
    "Vehicle Upgrade Console": "Vehicle Upgrade Console (Below Zero)",
    "Vending Machine": "Vending Machine (Below Zero)",
    "Vertical Connector": "Vertical Connector (Below Zero)",
    "Violet Beau": "Violet Beau (Below Zero)",
    "Vortex Torpedo": "Vortex Torpedo (Below Zero)",
    "Voxel Shrub": "Voxel Shrub (Below Zero)",
    "Walkthrough": "Walkthrough (Below Zero)",
    "Wall Locker": "Wall Locker (Below Zero)",
    "Wall Planter": "Wall Planter (Below Zero)",
    "Wall Shelves": "Wall Shelves (Below Zero)",
    "Water Filtration Machine": "Water Filtration Machine (Below Zero)",
    "Waterproof Locker": "Waterproof Locker (Below Zero)",
    "Window": "Window (Below Zero)",
    "Wiring Kit": "Wiring Kit (Below Zero)",
    "X Compartment": "X Compartment (Below Zero)",
}

templates = {
    "Template:!": "Template:! (BZ)",
    "Template:!/doc": "Template:!/doc (BZ)",
    "Template:Arctic Fauna": "Template:Arctic Fauna (BZ)",
    "Template:Biome2": "Template:Biome2 (BZ)",
    "Template:CC-BY-SA": "Template:CC-BY-SA (BZ)",
    "Template:CC-BY-SA/doc": "Template:CC-BY-SA/doc (BZ)",
    "Template:Caption": "Template:Caption (BZ)",
    "Template:Caption/doc": "Template:Caption/doc (BZ)",
    "Template:Cat main": "Template:Cat main (BZ)",
    "Template:Cc-by-sa-3.0": "Template:Cc-by-sa-3.0 (BZ)",
    "Template:Cc-by-sa-3.0/doc": "Template:Cc-by-sa-3.0/doc (BZ)",
    "Template:Citation Needed": "Template:Citation Needed (BZ)",
    "Template:Craftable": "Template:Craftable (BZ)",
    "Template:Databank": "Template:Databank (BZ)",
    "Template:Databank/doc": "Template:Databank/doc (BZ)",
    "Template:Databank2": "Template:Databank2 (BZ)",
    "Template:Databank2/doc": "Template:Databank2/doc (BZ)",
    "Template:Deceased": "Template:Deceased (BZ)",
    "Template:Deceased/doc": "Template:Deceased/doc (BZ)",
    "Template:Delete": "Template:Delete (BZ)",
    "Template:Delete/doc": "Template:Delete/doc (BZ)",
    "Template:Disambig": "Template:Disambig (BZ)",
    "Template:Disambig/doc": "Template:Disambig/doc (BZ)",
    "Template:Disambiguate": "Template:Disambiguate (BZ)",
    "Template:Documentation": "Template:Documentation (BZ)",
    "Template:Documentation/doc": "Template:Documentation/doc (BZ)",
    "Template:Experimental": "Template:Experimental (BZ)",
    "Template:Experimental/doc": "Template:Experimental/doc (BZ)",
    "Template:Fairuse": "Template:Fairuse (BZ)",
    "Template:Fairuse/doc": "Template:Fairuse/doc (BZ)",
    "Template:Fauna": "Template:Fauna (BZ)",
    "Template:Flora": "Template:Flora (BZ)",
    "Template:From Wikimedia": "Template:From Wikimedia (BZ)",
    "Template:From Wikimedia/doc": "Template:From Wikimedia/doc (BZ)",
    "Template:Hatnote": "Template:Hatnote (BZ)",
    "Template:Header": "Template:Header (BZ)",
    "Template:IDRow": "Template:IDRow (BZ)",
    "Template:IDRow/doc": "Template:IDRow/doc (BZ)",
    "Template:IDTable": "Template:IDTable (BZ)",
    "Template:IDTable/doc": "Template:IDTable/doc (BZ)",
    "Template:Id": "Template:Id (BZ)",
    "Template:Infobox": "Template:Infobox (BZ)",
    "Template:Infobox book": "Template:Infobox book (BZ)",
    "Template:Infobox book/doc": "Template:Infobox book/doc (BZ)",
    "Template:Infobox episode": "Template:Infobox episode (BZ)",
    "Template:Infobox episode/doc": "Template:Infobox episode/doc (BZ)",
    "Template:Infobox item": "Template:Infobox item (BZ)",
    "Template:Infobox item/doc": "Template:Infobox item/doc (BZ)",
    "Template:Infobox location": "Template:Infobox location (BZ)",
    "Template:Infobox location/doc": "Template:Infobox location/doc (BZ)",
    "Template:Infobox quest": "Template:Infobox quest (BZ)",
    "Template:Infobox quest/doc": "Template:Infobox quest/doc (BZ)",
    "Template:Key": "Template:Key (BZ)",
    "Template:Key/PS4": "Template:Key/PS4 (BZ)",
    "Template:Key/Switch": "Template:Key/Switch (BZ)",
    "Template:Key/doc": "Template:Key/doc (BZ)",
    "Template:Key xbox": "Template:Key xbox (BZ)",
    "Template:Key xbox/doc": "Template:Key xbox/doc (BZ)",
    "Template:Main": "Template:Main (BZ)",
    "Template:Navbar": "Template:Navbar (BZ)",
    "Template:Navbox": "Template:Navbox (BZ)",
    "Template:Navbox/doc": "Template:Navbox/doc (BZ)",
    "Template:Navbox2": "Template:Navbox2 (BZ)",
    "Template:Navbox2/doc": "Template:Navbox2/doc (BZ)",
    "Template:Navbox Biomes": "Template:Navbox Biomes (BZ)",
    "Template:Navbox Characters": "Template:Navbox Characters (BZ)",
    "Template:Navbox Corals": "Template:Navbox Corals (BZ)",
    "Template:Navbox Fauna": "Template:Navbox Fauna (BZ)",
    "Template:Navbox Flora": "Template:Navbox Flora (BZ)",
    "Template:Navbox Items": "Template:Navbox Items (BZ)",
    "Template:Navbox Seabase Modules": "Template:Navbox Seabase Modules (BZ)",
    "Template:NotInGame": "Template:NotInGame (BZ)",
    "Template:Other free": "Template:Other free (BZ)",
    "Template:Other free/doc": "Template:Other free/doc (BZ)",
    "Template:PD": "Template:PD (BZ)",
    "Template:PD/doc": "Template:PD/doc (BZ)",
    "Template:Permission": "Template:Permission (BZ)",
    "Template:Permission/doc": "Template:Permission/doc (BZ)",
    "Template:Portal/Component/Navigation": "Template:Portal/Component/Navigation (BZ)",
    "Template:Portal/Component/Social Media": "Template:Portal/Component/Social Media (BZ)",
    "Template:Portal/Component/Tabber": "Template:Portal/Component/Tabber (BZ)",
    "Template:Portal/Component/Useful Links": "Template:Portal/Component/Useful Links (BZ)",
    "Template:Portal/Component/Welcome": "Template:Portal/Component/Welcome (BZ)",
    "Template:Purge": "Template:Purge (BZ)",
    "Template:Quote": "Template:Quote (BZ)",
    "Template:Quote/doc": "Template:Quote/doc (BZ)",
    "Template:Quote2": "Template:Quote2 (BZ)",
    "Template:Quote2/doc": "Template:Quote2/doc (BZ)",
    "Template:Recipe": "Template:Recipe (BZ)",
    "Template:Recipe/doc": "Template:Recipe/doc (BZ)",
    "Template:Recipe2": "Template:Recipe2 (BZ)",
    "Template:Recipe2/doc": "Template:Recipe2/doc (BZ)",
    "Template:Repeat": "Template:Repeat (BZ)",
    "Template:Repeat/doc": "Template:Repeat/doc (BZ)",
    "Template:Self": "Template:Self (BZ)",
    "Template:Self/doc": "Template:Self/doc (BZ)",
    "Template:SimilarName": "Template:SimilarName (BZ)",
    "Template:SmallSpoiler": "Template:SmallSpoiler (BZ)",
    "Template:SmallSpoiler/doc": "Template:SmallSpoiler/doc (BZ)",
    "Template:SoundTable": "Template:SoundTable (BZ)",
    "Template:SoundTable/Row": "Template:SoundTable/Row (BZ)",
    "Template:SoundTable/doc": "Template:SoundTable/doc (BZ)",
    "Template:Spoiler": "Template:Spoiler (BZ)",
    "Template:Spoilersection": "Template:Spoilersection (BZ)",
    "Template:Spoilersection/doc": "Template:Spoilersection/doc (BZ)",
    "Template:Str": "Template:Str (BZ)",
    "Template:SubnauticaLink": "Template:SubnauticaLink (BZ)",
    "Template:SubnauticaLink2": "Template:SubnauticaLink2 (BZ)",
    "Template:SubnauticaLinkThe": "Template:SubnauticaLinkThe (BZ)",
    "Template:T": "Template:T (BZ)",
    "Template:T/doc": "Template:T/doc (BZ)",
    "Template:T/piece": "Template:T/piece (BZ)",
    "Template:T/piece/doc": "Template:T/piece/doc (BZ)",
    "Template:Warning": "Template:Warning (BZ)",
}

files = {
    "File:2015-04-14 00101.jpg": "File:2015-04-14 00101 (BZ).jpg",
    "File:20160905093632 1.jpg": "File:20160905093632 1 (BZ).jpg",
    "File:20161118001107 1.jpg": "File:20161118001107 1 (BZ).jpg",
    "File:30SecondsCombined.ogg": "File:30SecondsCombined (BZ).ogg",
    "File:42FF17DE-5D95-429D-B22D-0950F3D47934.png": "File:42FF17DE-5D95-429D-B22D-0950F3D47934 (BZ).png",
    "File:4546B.jpg": "File:4546B (BZ).jpg",
    "File:51316487 2297072743910702 561692761225600124 n.jpg": "File:51316487 2297072743910702 561692761225600124 n (BZ).jpg",
    "File:7B292366-9745-467E-8337-FC1703B7467F.png": "File:7B292366-9745-467E-8337-FC1703B7467F (BZ).png",
    "File:994AF4BC-8079-4090-81E9-DB254C971BC9.png": "File:994AF4BC-8079-4090-81E9-DB254C971BC9 (BZ).png",
    "File:9FDA5298-888C-4959-814C-1307735821B9 1 201 a.jpeg": "File:9FDA5298-888C-4959-814C-1307735821B9 1 201 a (BZ).jpeg",
    "File:A94897BF-4981-4CF5-8DC0-930BC955930A.png": "File:A94897BF-4981-4CF5-8DC0-930BC955930A (BZ).png",
    "File:AWESOME.png": "File:AWESOME (BZ).png",
    "File:Advanced Wiring Kit.png": "File:Advanced Wiring Kit (BZ).png",
    "File:Aerogel.png": "File:Aerogel (BZ).png",
    "File:Air Bladder.png": "File:Air Bladder (BZ).png",
    "File:Air Pumps PDA Encyclopedia.png": "File:Air Pumps PDA Encyclopedia (BZ).png",
    "File:Al-An.png": "File:Al-An (BZ).png",
    "File:Al-an.png": "File:Al-an (BZ).png",
    "File:AlexRies-PenguinFoot.png": "File:AlexRies-PenguinFoot (BZ).png",
    "File:AlexRies-PenguinVariants.png": "File:AlexRies-PenguinVariants (BZ).png",
    "File:Alex Ries.jpg": "File:Alex Ries (BZ).jpg",
    "File:Alex seal01B.png": "File:Alex seal01B (BZ).png",
    "File:Alex sealVARIANTS02.png": "File:Alex sealVARIANTS02 (BZ).png",
    "File:Alex titanholefishsymbiote3B.png": "File:Alex titanholefishsymbiote3B (BZ).png",
    "File:Alien Containment.png": "File:Alien Containment (BZ).png",
    "File:Alien Penguin B.jpg": "File:Alien Penguin B (BZ).jpg",
    "File:Alien Robot.png": "File:Alien Robot (BZ).png",
    "File:AlterraLogo.png": "File:AlterraLogo (BZ).png",
    "File:AluminumOxideLarge.png": "File:AluminumOxideLarge (BZ).png",
    "File:Amoeboid Fauna.png": "File:Amoeboid Fauna (BZ).png",
    "File:Ancient Skeleton.png": "File:Ancient Skeleton (BZ).png",
    "File:Andrew Jones.jpg": "File:Andrew Jones (BZ).jpg",
    "File:Aquarium.png": "File:Aquarium (BZ).png",
    "File:Arcade Gorge Toy.png": "File:Arcade Gorge Toy (BZ).png",
    "File:ArcticLandmassRocket.png": "File:ArcticLandmassRocket (BZ).png",
    "File:ArcticLargePlants.png": "File:ArcticLargePlants (BZ).png",
    "File:ArcticPeeperLogo.png": "File:ArcticPeeperLogo (BZ).png",
    "File:Arctic Concept Art.jpg": "File:Arctic Concept Art (BZ).jpg",
    "File:Arctic Peeper Fauna.png": "File:Arctic Peeper Fauna (BZ).png",
    "File:Arctic Ray Fauna.png": "File:Arctic Ray Fauna (BZ).png",
    "File:Arctic Spires LowRes.jpg": "File:Arctic Spires LowRes (BZ).jpg",
    "File:Arctic Trench LowRes.jpg": "File:Arctic Trench LowRes (BZ).jpg",
    "File:Arctic expansionCreatures WIP Round01E2 pb.jpg": "File:Arctic expansionCreatures WIP Round01E2 pb (BZ).jpg",
    "File:Arctic kelp 08 FINAL.jpg": "File:Arctic kelp 08 FINAL (BZ).jpg",
    "File:Arcticoverview boxedin 2.png": "File:Arcticoverview boxedin 2 (BZ).png",
    "File:Arrow-right (1).png": "File:Arrow-right (1) (BZ).png",
    "File:Arrow Ray Fauna.png": "File:Arrow Ray Fauna (BZ).png",
    "File:Audio.png": "File:Audio (BZ).png",
    "File:Audio Hover.png": "File:Audio Hover (BZ).png",
    "File:Badge-1-0.png": "File:Badge-1-0 (BZ).png",
    "File:Badge-1-1.png": "File:Badge-1-1 (BZ).png",
    "File:Badge-1-2.png": "File:Badge-1-2 (BZ).png",
    "File:Badge-1-3.png": "File:Badge-1-3 (BZ).png",
    "File:Badge-1-4.png": "File:Badge-1-4 (BZ).png",
    "File:Badge-1-5.png": "File:Badge-1-5 (BZ).png",
    "File:Badge-1-6.png": "File:Badge-1-6 (BZ).png",
    "File:Badge-1-7.png": "File:Badge-1-7 (BZ).png",
    "File:Badge-2-0.png": "File:Badge-2-0 (BZ).png",
    "File:Badge-2-1.png": "File:Badge-2-1 (BZ).png",
    "File:Badge-2-2.png": "File:Badge-2-2 (BZ).png",
    "File:Badge-2-3.png": "File:Badge-2-3 (BZ).png",
    "File:Badge-2-4.png": "File:Badge-2-4 (BZ).png",
    "File:Badge-2-5.png": "File:Badge-2-5 (BZ).png",
    "File:Badge-2-6.png": "File:Badge-2-6 (BZ).png",
    "File:Badge-2-7.png": "File:Badge-2-7 (BZ).png",
    "File:Badge-3-0.png": "File:Badge-3-0 (BZ).png",
    "File:Badge-3-1.png": "File:Badge-3-1 (BZ).png",
    "File:Badge-3-2.png": "File:Badge-3-2 (BZ).png",
    "File:Badge-3-3.png": "File:Badge-3-3 (BZ).png",
    "File:Badge-3-4.png": "File:Badge-3-4 (BZ).png",
    "File:Badge-3-5.png": "File:Badge-3-5 (BZ).png",
    "File:Badge-3-6.png": "File:Badge-3-6 (BZ).png",
    "File:Badge-3-7.png": "File:Badge-3-7 (BZ).png",
    "File:Badge-4-0.png": "File:Badge-4-0 (BZ).png",
    "File:Badge-4-7.png": "File:Badge-4-7 (BZ).png",
    "File:Badge-caffeinated.png": "File:Badge-caffeinated (BZ).png",
    "File:Badge-edit-0.png": "File:Badge-edit-0 (BZ).png",
    "File:Badge-edit-1.png": "File:Badge-edit-1 (BZ).png",
    "File:Badge-edit-5.png": "File:Badge-edit-5 (BZ).png",
    "File:Badge-edit-6.png": "File:Badge-edit-6 (BZ).png",
    "File:Badge-edit-7.png": "File:Badge-edit-7 (BZ).png",
    "File:Badge-love-2.png": "File:Badge-love-2 (BZ).png",
    "File:Badge-love-3.png": "File:Badge-love-3 (BZ).png",
    "File:Badge-love-4.png": "File:Badge-love-4 (BZ).png",
    "File:Badge-picture-6.png": "File:Badge-picture-6 (BZ).png",
    "File:Badge-picture-7.png": "File:Badge-picture-7 (BZ).png",
    "File:Bar Table.png": "File:Bar Table (BZ).png",
    "File:Base-attached Air Pump.png": "File:Base-attached Air Pump (BZ).png",
    "File:Base Large Aquarium Notes.jpg": "File:Base Large Aquarium Notes (BZ).jpg",
    "File:Base Pipe Connector.png": "File:Base Pipe Connector (BZ).png",
    "File:Base exterior modules group.png": "File:Base exterior modules group (BZ).png",
    "File:Base interior modules group.png": "File:Base interior modules group (BZ).png",
    "File:Base interior pieces group.png": "File:Base interior pieces group (BZ).png",
    "File:Base miscellaneous group.png": "File:Base miscellaneous group (BZ).png",
    "File:Base pieces group.png": "File:Base pieces group (BZ).png",
    "File:Basic Double Bed.png": "File:Basic Double Bed (BZ).png",
    "File:Basic Plant Pot.png": "File:Basic Plant Pot (BZ).png",
    "File:Battery.png": "File:Battery (BZ).png",
    "File:Battery Charger.png": "File:Battery Charger (BZ).png",
    "File:Beacon.png": "File:Beacon (BZ).png",
    "File:Beacon Fragment.png": "File:Beacon Fragment (BZ).png",
    "File:Beacon Ping.png": "File:Beacon Ping (BZ).png",
    "File:Beaconmodel.png": "File:Beaconmodel (BZ).png",
    "File:Bed.png": "File:Bed (BZ).png",
    "File:Bed 2.png": "File:Bed 2 (BZ).png",
    "File:Bench.png": "File:Bench (BZ).png",
    "File:BendyFinale(FinalRender).png": "File:BendyFinale(FinalRender) (BZ).png",
    "File:Benzene.png": "File:Benzene (BZ).png",
    "File:Big Filtered Water.png": "File:Big Filtered Water (BZ).png",
    "File:BiomeMap.png": "File:BiomeMap (BZ).png",
    "File:BiomeMapNew.png": "File:BiomeMapNew (BZ).png",
    "File:Bioreactor.png": "File:Bioreactor (BZ).png",
    "File:Bioreactor Icon.png": "File:Bioreactor Icon (BZ).png",
    "File:Biter BK variant.jpg": "File:Biter BK variant (BZ).jpg",
    "File:Biterbloodversion.png": "File:Biterbloodversion (BZ).png",
    "File:Black Smokers.jpg": "File:Black Smokers (BZ).jpg",
    "File:Bladderfish-0.png": "File:Bladderfish-0 (BZ).png",
    "File:Bladderfish.png": "File:Bladderfish (BZ).png",
    "File:Bladderfish1.jpg": "File:Bladderfish1 (BZ).jpg",
    "File:Bladderfish2.jpg": "File:Bladderfish2 (BZ).jpg",
    "File:Bladderfish3.jpg": "File:Bladderfish3 (BZ).jpg",
    "File:Bladderfish4.jpg": "File:Bladderfish4 (BZ).jpg",
    "File:Bladderfish Fauna.png": "File:Bladderfish Fauna (BZ).png",
    "File:Bladderfishsizeref.jpg": "File:Bladderfishsizeref (BZ).jpg",
    "File:Bleach.png": "File:Bleach (BZ).png",
    "File:Blighter10.jpg": "File:Blighter10 (BZ).jpg",
    "File:Blighter6.jpg": "File:Blighter6 (BZ).jpg",
    "File:Blighter7.jpg": "File:Blighter7 (BZ).jpg",
    "File:Blighter8.jpg": "File:Blighter8 (BZ).jpg",
    "File:Blighter9.jpg": "File:Blighter9 (BZ).jpg",
    "File:BlighterBiterCA.jpg": "File:BlighterBiterCA (BZ).jpg",
    "File:Blighter Fauna.png": "File:Blighter Fauna (BZ).png",
    "File:Blood Hoopfish Fauna.png": "File:Blood Hoopfish Fauna (BZ).png",
    "File:Blood Oil.png": "File:Blood Oil (BZ).png",
    "File:Bloodgrass Flora.png": "File:Bloodgrass Flora (BZ).png",
    "File:BloomPlanktonFlare.jpg": "File:BloomPlanktonFlare (BZ).jpg",
    "File:BloomPlanktonTorch.jpg": "File:BloomPlanktonTorch (BZ).jpg",
    "File:Bloomplankton-1.png": "File:Bloomplankton-1 (BZ).png",
    "File:Blue Barnacles Flora.png": "File:Blue Barnacles Flora (BZ).png",
    "File:Blue Palm Flora.png": "File:Blue Palm Flora (BZ).png",
    "File:Blue Tablet.png": "File:Blue Tablet (BZ).png",
    "File:Boneshark-2.png": "File:Boneshark-2 (BZ).png",
    "File:Boneshark Fauna.png": "File:Boneshark Fauna (BZ).png",
    "File:Boomerang-0.png": "File:Boomerang-0 (BZ).png",
    "File:Boomerang.png": "File:Boomerang (BZ).png",
    "File:Boomerang Fauna.png": "File:Boomerang Fauna (BZ).png",
    "File:Brain Coral Coral.png": "File:Brain Coral Coral (BZ).png",
    "File:Brain Coral Fauna.png": "File:Brain Coral Fauna (BZ).png",
    "File:Brandt Wojak.jpg": "File:Brandt Wojak (BZ).jpg",
    "File:Brian Cummings.jpg": "File:Brian Cummings (BZ).jpg",
    "File:Brinewing Fauna.png": "File:Brinewing Fauna (BZ).png",
    "File:Brute Shark.png": "File:Brute Shark (BZ).png",
    "File:Brute Shark Fauna.png": "File:Brute Shark Fauna (BZ).png",
    "File:Builder.png": "File:Builder (BZ).png",
    "File:Bulbo Tree Sample.png": "File:Bulbo Tree Sample (BZ).png",
    "File:Bulkhead.png": "File:Bulkhead (BZ).png",
    "File:Camera Drone.png": "File:Camera Drone (BZ).png",
    "File:Camera Drone Ping.png": "File:Camera Drone Ping (BZ).png",
    "File:Capture.png": "File:Capture (BZ).png",
    "File:Category Advanced Materials.png": "File:Category Advanced Materials (BZ).png",
    "File:Category Basic Materials.png": "File:Category Basic Materials (BZ).png",
    "File:Category Cooked Food.png": "File:Category Cooked Food (BZ).png",
    "File:Category Cured Food.png": "File:Category Cured Food (BZ).png",
    "File:Category Deployables.png": "File:Category Deployables (BZ).png",
    "File:Category Electronics.png": "File:Category Electronics (BZ).png",
    "File:Category Equipment.png": "File:Category Equipment (BZ).png",
    "File:Category Tools.png": "File:Category Tools (BZ).png",
    "File:Category Water.png": "File:Category Water (BZ).png",
    "File:Cave Bush-0.png": "File:Cave Bush-0 (BZ).png",
    "File:Cave Sulfur.png": "File:Cave Sulfur (BZ).png",
    "File:Centrifuge.png": "File:Centrifuge (BZ).png",
    "File:Chair.png": "File:Chair (BZ).png",
    "File:Chair 2.png": "File:Chair 2 (BZ).png",
    "File:Chair 3.png": "File:Chair 3 (BZ).png",
    "File:Charlie Cleveland.jpg": "File:Charlie Cleveland (BZ).jpg",
    "File:Cheeky Creature 1.jpg": "File:Cheeky Creature 1 (BZ).jpg",
    "File:Cheeky Creature 2.jpg": "File:Cheeky Creature 2 (BZ).jpg",
    "File:Chelicerate Fauna.png": "File:Chelicerate Fauna (BZ).png",
    "File:Chic Plant Pot.png": "File:Chic Plant Pot (BZ).png",
    "File:Chinese Potato-0.png": "File:Chinese Potato-0 (BZ).png",
    "File:Chinese Potato.png": "File:Chinese Potato (BZ).png",
    "File:Chinese Potato Plant.png": "File:Chinese Potato Plant (BZ).png",
    "File:Chinese Potato Plant Flora.png": "File:Chinese Potato Plant Flora (BZ).png",
    "File:Coffee.png": "File:Coffee (BZ).png",
    "File:Coffee 1.ogg": "File:Coffee 1 (BZ).ogg",
    "File:Coffee 2.ogg": "File:Coffee 2 (BZ).ogg",
    "File:Coffee Americano.png": "File:Coffee Americano (BZ).png",
    "File:Coffee Vending Machine.png": "File:Coffee Vending Machine (BZ).png",
    "File:Colin Knueppel.jpg": "File:Colin Knueppel (BZ).jpg",
    "File:Combops4circle.png": "File:Combops4circle (BZ).png",
    "File:Combops4sq.png": "File:Combops4sq (BZ).png",
    "File:Combops4tri.png": "File:Combops4tri (BZ).png",
    "File:Combops4x.png": "File:Combops4x (BZ).png",
    "File:Command Chair.png": "File:Command Chair (BZ).png",
    "File:Community-Page-Header.jpg": "File:Community-Page-Header (BZ).jpg",
    "File:Community-header-background": "File:Community-header-background (BZ)",
    "File:Community image 1405012698.jpg": "File:Community image 1405012698 (BZ).jpg",
    "File:Compass.png": "File:Compass (BZ).png",
    "File:Composite Plant Pot.png": "File:Composite Plant Pot (BZ).png",
    "File:Computer Chip.png": "File:Computer Chip (BZ).png",
    "File:Cooked Bladderfish.png": "File:Cooked Bladderfish (BZ).png",
    "File:Cooked Boomerang.png": "File:Cooked Boomerang (BZ).png",
    "File:Cooked Eyeye.png": "File:Cooked Eyeye (BZ).png",
    "File:Cooked Hoopfish.png": "File:Cooked Hoopfish (BZ).png",
    "File:Cooked Peeper.png": "File:Cooked Peeper (BZ).png",
    "File:Cooked Spinefish.png": "File:Cooked Spinefish (BZ).png",
    "File:Copper Ore.png": "File:Copper Ore (BZ).png",
    "File:Copper Wire.png": "File:Copper Wire (BZ).png",
    "File:Coral Tube Sample.png": "File:Coral Tube Sample (BZ).png",
    "File:Coral reef Spiky trap.jpg": "File:Coral reef Spiky trap (BZ).jpg",
    "File:Coral reef twisty bridges.jpg": "File:Coral reef twisty bridges (BZ).jpg",
    "File:Cory Strader.png": "File:Cory Strader (BZ).png",
    "File:Corymedkitref.png": "File:Corymedkitref (BZ).png",
    "File:Counter.png": "File:Counter (BZ).png",
    "File:Crabsnake Fauna.png": "File:Crabsnake Fauna (BZ).png",
    "File:Crabsquid.png": "File:Crabsquid (BZ).png",
    "File:Crashfish.png": "File:Crashfish (BZ).png",
    "File:Crashfish Egg.png": "File:Crashfish Egg (BZ).png",
    "File:Crashfish Fauna.png": "File:Crashfish Fauna (BZ).png",
    "File:Crater.png": "File:Crater (BZ).png",
    "File:Creature Decoy.png": "File:Creature Decoy (BZ).png",
    "File:Creepvine.png": "File:Creepvine (BZ).png",
    "File:Creepvine Flora.png": "File:Creepvine Flora (BZ).png",
    "File:Creepvine Sample.png": "File:Creepvine Sample (BZ).png",
    "File:Creepvine Seed Cluster.png": "File:Creepvine Seed Cluster (BZ).png",
    "File:Crested ReaperAlex.jpg": "File:Crested ReaperAlex (BZ).jpg",
    "File:Crystalline Sulfur.png": "File:Crystalline Sulfur (BZ).png",
    "File:Crystalline cloakmouth by abiogenisis-d4nyn55.jpg": "File:Crystalline cloakmouth by abiogenisis-d4nyn55 (BZ).jpg",
    "File:Cured Bladderfish.png": "File:Cured Bladderfish (BZ).png",
    "File:Cured Boomerang.png": "File:Cured Boomerang (BZ).png",
    "File:Cured Eyeye.png": "File:Cured Eyeye (BZ).png",
    "File:Cured Hoopfish.png": "File:Cured Hoopfish (BZ).png",
    "File:Cured Spinefish.png": "File:Cured Spinefish (BZ).png",
    "File:Cute Fish Fauna.png": "File:Cute Fish Fauna (BZ).png",
    "File:Cyclops.png": "File:Cyclops (BZ).png",
    "File:Cylindrical sample flask.png": "File:Cylindrical sample flask (BZ).png",
    "File:DA976FAE-35B0-4EE9-98AB-D75B2848FD46.png": "File:DA976FAE-35B0-4EE9-98AB-D75B2848FD46 (BZ).png",
    "File:Damaged Propulsion Cannon.png": "File:Damaged Propulsion Cannon (BZ).png",
    "File:Damaged Seaglide.png": "File:Damaged Seaglide (BZ).png",
    "File:Damaged Stasis Rifle.png": "File:Damaged Stasis Rifle (BZ).png",
    "File:Damaged Transfuser.png": "File:Damaged Transfuser (BZ).png",
    "File:Data Box.png": "File:Data Box (BZ).png",
    "File:David Kalina.png": "File:David Kalina (BZ).png",
    "File:Deep Shroom.png": "File:Deep Shroom (BZ).png",
    "File:Degasi.png": "File:Degasi (BZ).png",
    "File:Degasi1.png": "File:Degasi1 (BZ).png",
    "File:DegasiReveal.png": "File:DegasiReveal (BZ).png",
    "File:Depleted Reactor Rod.png": "File:Depleted Reactor Rod (BZ).png",
    "File:Desk.png": "File:Desk (BZ).png",
    "File:Diamond.png": "File:Diamond (BZ).png",
    "File:DiamondResourceDepositNew.png": "File:DiamondResourceDepositNew (BZ).png",
    "File:DiscordLogo.png": "File:DiscordLogo (BZ).png",
    "File:Discus Fauna.png": "File:Discus Fauna (BZ).png",
    "File:Disease Research Facility Skeleton.png": "File:Disease Research Facility Skeleton (BZ).png",
    "File:Disinfected Water.png": "File:Disinfected Water (BZ).png",
    "File:Dive Reel.png": "File:Dive Reel (BZ).png",
    "File:Dmitry IceColumns final lowRes.jpg": "File:Dmitry IceColumns final lowRes (BZ).jpg",
    "File:DoubleShellPlant2.jpg": "File:DoubleShellPlant2 (BZ).jpg",
    "File:Doubleshellplant2.jpg": "File:Doubleshellplant2 (BZ).jpg",
    "File:Downarrow.png": "File:Downarrow (BZ).png",
    "File:Download.jpeg": "File:Download (BZ).jpeg",
    "File:Download.jpg": "File:Download (BZ).jpg",
    "File:Download (3).jpeg": "File:Download (3) (BZ).jpeg",
    "File:Download (4).jpeg": "File:Download (4) (BZ).jpeg",
    "File:Download (5).jpeg": "File:Download (5) (BZ).jpeg",
    "File:Dragonfly.jpeg": "File:Dragonfly (BZ).jpeg",
    "File:DrillableSilver.png": "File:DrillableSilver (BZ).png",
    "File:Drillable Copper Ore Deposit.png": "File:Drillable Copper Ore Deposit (BZ).png",
    "File:Drillable Gold Deposit.png": "File:Drillable Gold Deposit (BZ).png",
    "File:Drillable Ion Cube Cluster.png": "File:Drillable Ion Cube Cluster (BZ).png",
    "File:Drillable Kyanite.png": "File:Drillable Kyanite (BZ).png",
    "File:Drillable Titanium Deposit.png": "File:Drillable Titanium Deposit (BZ).png",
    "File:E6D7E07A-49F6-42EE-B31F-BFC22CBF996C.png": "File:E6D7E07A-49F6-42EE-B31F-BFC22CBF996C (BZ).png",
    "File:EarlyPinnicarid.jpg": "File:EarlyPinnicarid (BZ).jpg",
    "File:EarlySquidshark.jpg": "File:EarlySquidshark (BZ).jpg",
    "File:Earthen Coral Tubes.png": "File:Earthen Coral Tubes (BZ).png",
    "File:Electron Microscope.png": "File:Electron Microscope (BZ).png",
    "File:Enameled Glass.png": "File:Enameled Glass (BZ).png",
    "File:Energy.png": "File:Energy (BZ).png",
    "File:Engine Efficiency Module.png": "File:Engine Efficiency Module (BZ).png",
    "File:Ennard(FinalRender).png": "File:Ennard(FinalRender) (BZ).png",
    "File:EpicGamesLogo.png": "File:EpicGamesLogo (BZ).png",
    "File:Ercticbyscotmacdooland.png": "File:Ercticbyscotmacdooland (BZ).png",
    "File:Example.png": "File:Example (BZ).png",
    "File:Exosuit Jet Jump Upgrade.png": "File:Exosuit Jet Jump Upgrade (BZ).png",
    "File:Experimental 1.png": "File:Experimental 1 (BZ).png",
    "File:Experimental 2.png": "File:Experimental 2 (BZ).png",
    "File:Exterior Growbed.png": "File:Exterior Growbed (BZ).png",
    "File:Exterior Growbed PDA Encyclopedia.png": "File:Exterior Growbed PDA Encyclopedia (BZ).png",
    "File:Eyeless Cyclops.png": "File:Eyeless Cyclops (BZ).png",
    "File:Eyeye-0.png": "File:Eyeye-0 (BZ).png",
    "File:Eyeye.png": "File:Eyeye (BZ).png",
    "File:Eyeye Fauna.png": "File:Eyeye Fauna (BZ).png",
    "File:F4CD6DFC-0C76-4DBD-923C-E1F923FCAFC3.png": "File:F4CD6DFC-0C76-4DBD-923C-E1F923FCAFC3 (BZ).png",
    "File:FFFEA980-BFB3-4584-A1E4-33405F82000E.jpg": "File:FFFEA980-BFB3-4584-A1E4-33405F82000E (BZ).jpg",
    "File:Fabricator.png": "File:Fabricator (BZ).png",
    "File:FabricatorMenu-Equipment.png": "File:FabricatorMenu-Equipment (BZ).png",
    "File:Fabricator Menu Advanced Materials.png": "File:Fabricator Menu Advanced Materials (BZ).png",
    "File:Fabricator Menu Cooked Food.png": "File:Fabricator Menu Cooked Food (BZ).png",
    "File:Fabricator Menu Cured Food.png": "File:Fabricator Menu Cured Food (BZ).png",
    "File:Fabricator Menu Electronics.png": "File:Fabricator Menu Electronics (BZ).png",
    "File:Fabricator Menu Materials.png": "File:Fabricator Menu Materials (BZ).png",
    "File:Fabricator Menu Tools.png": "File:Fabricator Menu Tools (BZ).png",
    "File:Fabricator Menu Water.png": "File:Fabricator Menu Water (BZ).png",
    "File:Fabricator menu deployables.png": "File:Fabricator menu deployables (BZ).png",
    "File:Favicon.ico": "File:Favicon (BZ).ico",
    "File:Feather Fish 02 Fauna.png": "File:Feather Fish 02 Fauna (BZ).png",
    "File:Feather Fish Fauna.png": "File:Feather Fish Fauna (BZ).png",
    "File:FemaleProtag.jpg": "File:FemaleProtag (BZ).jpg",
    "File:Female reinforced suit sketchfab.jpg": "File:Female reinforced suit sketchfab (BZ).jpg",
    "File:Female still suit sketchfab.jpg": "File:Female still suit sketchfab (BZ).jpg",
    "File:Fiber Mesh.png": "File:Fiber Mesh (BZ).png",
    "File:Filtered Water.png": "File:Filtered Water (BZ).png",
    "File:Fins.png": "File:Fins (BZ).png",
    "File:Fire Extinguisher.png": "File:Fire Extinguisher (BZ).png",
    "File:First Aid Kit.png": "File:First Aid Kit (BZ).png",
    "File:Flare.png": "File:Flare (BZ).png",
    "File:Flashlight.png": "File:Flashlight (BZ).png",
    "File:Floater.png": "File:Floater (BZ).png",
    "File:Floater Fauna-0.png": "File:Floater Fauna-0 (BZ).png",
    "File:Floating Air Pump.png": "File:Floating Air Pump (BZ).png",
    "File:Floatingstoragemodel.png": "File:Floatingstoragemodel (BZ).png",
    "File:Floodlight.png": "File:Floodlight (BZ).png",
    "File:FoodLowCombined.ogg": "File:FoodLowCombined (BZ).ogg",
    "File:FoodVeryCriticalCombined.ogg": "File:FoodVeryCriticalCombined (BZ).ogg",
    "File:Foundation.png": "File:Foundation (BZ).png",
    "File:Fox3d-entertainment-maproom.jpg": "File:Fox3d-entertainment-maproom (BZ).jpg",
    "File:Fox3d-entertainment-violet-beau.jpg": "File:Fox3d-entertainment-violet-beau (BZ).jpg",
    "File:Front View.jpg": "File:Front View (BZ).jpg",
    "File:Fungal Sample.png": "File:Fungal Sample (BZ).png",
    "File:Gargantuan Skull.png": "File:Gargantuan Skull (BZ).png",
    "File:Garryfish Fauna.png": "File:Garryfish Fauna (BZ).png",
    "File:Gasopod Fauna.png": "File:Gasopod Fauna (BZ).png",
    "File:Gel Sack.png": "File:Gel Sack (BZ).png",
    "File:Gel Sack Data Bank Image.png": "File:Gel Sack Data Bank Image (BZ).png",
    "File:Gel Sack Flora.png": "File:Gel Sack Flora (BZ).png",
    "File:Gel Sack Spores.png": "File:Gel Sack Spores (BZ).png",
    "File:Ghost Leviathan Fauna.png": "File:Ghost Leviathan Fauna (BZ).png",
    "File:Ghost Weed Flora.png": "File:Ghost Weed Flora (BZ).png",
    "File:Giphy.gif": "File:Giphy (BZ).gif",
    "File:Girls Concept.jpg": "File:Girls Concept (BZ).jpg",
    "File:Glass.png": "File:Glass (BZ).png",
    "File:Glow Whale Fauna.png": "File:Glow Whale Fauna (BZ).png",
    "File:Glow whale": "File:Glow whale (BZ)",
    "File:Gold.png": "File:Gold (BZ).png",
    "File:Grabsquid.jpg": "File:Grabsquid (BZ).jpg",
    "File:Grav Trap.png": "File:Grav Trap (BZ).png",
    "File:Grav Trap Fragment.png": "File:Grav Trap Fragment (BZ).png",
    "File:Gravsphere.png": "File:Gravsphere (BZ).png",
    "File:Grub Basket Flora.png": "File:Grub Basket Flora (BZ).png",
    "File:HUDStats.gif": "File:HUDStats (BZ).gif",
    "File:Habitat Builder.png": "File:Habitat Builder (BZ).png",
    "File:Hatch.png": "File:Hatch (BZ).png",
    "File:Header.jpg": "File:Header (BZ).jpg",
    "File:Hi-Res Rock Puncher Concept Art.jpg": "File:Hi-Res Rock Puncher Concept Art (BZ).jpg",
    "File:High Capacity O₂ Tank.png": "File:High Capacity O₂ Tank (BZ).png",
    "File:High Capacity Tank.png": "File:High Capacity Tank (BZ).png",
    "File:Holefish Fauna.png": "File:Holefish Fauna (BZ).png",
    "File:Hoop Fish (Blood version) Model.png": "File:Hoop Fish (Blood version) Model (BZ).png",
    "File:Hoopfish-0.png": "File:Hoopfish-0 (BZ).png",
    "File:Hoopfish.png": "File:Hoopfish (BZ).png",
    "File:Hoopfish4.jpg": "File:Hoopfish4 (BZ).jpg",
    "File:Hoopfish5.jpg": "File:Hoopfish5 (BZ).jpg",
    "File:Hoopfish6.jpg": "File:Hoopfish6 (BZ).jpg",
    "File:Hoopfish7.jpg": "File:Hoopfish7 (BZ).jpg",
    "File:Hoopfish Fauna.png": "File:Hoopfish Fauna (BZ).png",
    "File:Hoverbike Vehicle.png": "File:Hoverbike Vehicle (BZ).png",
    "File:Hoverfish Fauna.png": "File:Hoverfish Fauna (BZ).png",
    "File:Hqdefault.jpg": "File:Hqdefault (BZ).jpg",
    "File:Hugh Jeremy.png": "File:Hugh Jeremy (BZ).png",
    "File:Hull Reinforcement.png": "File:Hull Reinforcement (BZ).png",
    "File:Hydrochloric Acid.png": "File:Hydrochloric Acid (BZ).png",
    "File:I-Corridor Glass.png": "File:I-Corridor Glass (BZ).png",
    "File:I Compartment.png": "File:I Compartment (BZ).png",
    "File:Ic LimestoneChunk 22743.png": "File:Ic LimestoneChunk 22743 (BZ).png",
    "File:Ic SandstoneChunk 22997.png": "File:Ic SandstoneChunk 22997 (BZ).png",
    "File:Ic ShaleChunk 23297.png": "File:Ic ShaleChunk 23297 (BZ).png",
    "File:IceWorm1.jpg": "File:IceWorm1 (BZ).jpg",
    "File:IceWorm2.jpg": "File:IceWorm2 (BZ).jpg",
    "File:IceWorm3.jpg": "File:IceWorm3 (BZ).jpg",
    "File:IceWorm4.jpg": "File:IceWorm4 (BZ).jpg",
    "File:Ice Worm Fauna.png": "File:Ice Worm Fauna (BZ).png",
    "File:Iceworm1.jpg": "File:Iceworm1 (BZ).jpg",
    "File:Iceworm2.jpg": "File:Iceworm2 (BZ).jpg",
    "File:Iceworm3.jpg": "File:Iceworm3 (BZ).jpg",
    "File:Iceworm4.jpg": "File:Iceworm4 (BZ).jpg",
    "File:IgnitedGolden(FinalRender).png": "File:IgnitedGolden(FinalRender) (BZ).png",
    "File:Image.jpeg": "File:Image (BZ).jpeg",
    "File:Image.jpg": "File:Image (BZ).jpg",
    "File:Image.png": "File:Image (BZ).png",
    "File:Image03.jpg": "File:Image03 (BZ).jpg",
    "File:Images.jpeg": "File:Images (BZ).jpeg",
    "File:Images.jpg": "File:Images (BZ).jpg",
    "File:Images (1).jpg": "File:Images (1) (BZ).jpg",
    "File:Incubator.jpg": "File:Incubator (BZ).jpg",
    "File:IndoorGrowbedEncy.png": "File:IndoorGrowbedEncy (BZ).png",
    "File:Indoor Growbed.png": "File:Indoor Growbed (BZ).png",
    "File:InfestationFinalRender.png": "File:InfestationFinalRender (BZ).png",
    "File:Ion Battery.png": "File:Ion Battery (BZ).png",
    "File:Ion Cube.png": "File:Ion Cube (BZ).png",
    "File:Ion Power Cell.png": "File:Ion Power Cell (BZ).png",
    "File:JBiol.png": "File:JBiol (BZ).png",
    "File:JComparison.png": "File:JComparison (BZ).png",
    "File:Jake Smith.jpg": "File:Jake Smith (BZ).jpg",
    "File:Jelly Plant Flora.png": "File:Jelly Plant Flora (BZ).png",
    "File:Jellyray.png": "File:Jellyray (BZ).png",
    "File:Jellyshroom Flora.png": "File:Jellyshroom Flora (BZ).png",
    "File:Jumper Fauna.png": "File:Jumper Fauna (BZ).png",
    "File:KHARAA sAMPLE.png": "File:KHARAA sAMPLE (BZ).png",
    "File:KharaaCyst.png": "File:KharaaCyst (BZ).png",
    "File:Kharaa Sample.png": "File:Kharaa Sample (BZ).png",
    "File:Kyanite.png": "File:Kyanite (BZ).png",
    "File:L-Corridor Glass.png": "File:L-Corridor Glass (BZ).png",
    "File:L Compartment.png": "File:L Compartment (BZ).png",
    "File:L Corridor.png": "File:L Corridor (BZ).png",
    "File:L Glass Compartment.png": "File:L Glass Compartment (BZ).png",
    "File:Lab Container.png": "File:Lab Container (BZ).png",
    "File:Lab Counter.png": "File:Lab Counter (BZ).png",
    "File:Lab Equipment 2-0.png": "File:Lab Equipment 2-0 (BZ).png",
    "File:Lab Equipment 3.png": "File:Lab Equipment 3 (BZ).png",
    "File:Lab Trash Can.png": "File:Lab Trash Can (BZ).png",
    "File:Ladder.png": "File:Ladder (BZ).png",
    "File:Lantern Fruit.png": "File:Lantern Fruit (BZ).png",
    "File:Lantern Tree-0.png": "File:Lantern Tree-0 (BZ).png",
    "File:Lantern Tree Flora.png": "File:Lantern Tree Flora (BZ).png",
    "File:Large Bird.png": "File:Large Bird (BZ).png",
    "File:Large Bird Trailer.png": "File:Large Bird Trailer (BZ).png",
    "File:Large Filtered Water.png": "File:Large Filtered Water (BZ).png",
    "File:Laser Cutter.png": "File:Laser Cutter (BZ).png",
    "File:Laser Cutter Fragment.png": "File:Laser Cutter Fragment (BZ).png",
    "File:Lava Lizard.png": "File:Lava Lizard (BZ).png",
    "File:Lavaboomerang.png": "File:Lavaboomerang (BZ).png",
    "File:Lead.jpg": "File:Lead (BZ).jpg",
    "File:Lead.png": "File:Lead (BZ).png",
    "File:Life-form rock puncher.png": "File:Life-form rock puncher (BZ).png",
    "File:Light Stick.png": "File:Light Stick (BZ).png",
    "File:Lightweight High Capacity Tank.png": "File:Lightweight High Capacity Tank (BZ).png",
    "File:Lily Paddler Fauna.png": "File:Lily Paddler Fauna (BZ).png",
    "File:LilypadWaterIslands LowRes.jpg": "File:LilypadWaterIslands LowRes (BZ).jpg",
    "File:Lilypad Highpoly WIP.png": "File:Lilypad Highpoly WIP (BZ).png",
    "File:Lilypad Islands Background.png": "File:Lilypad Islands Background (BZ).png",
    "File:Lilypad Islands Trunk Base 01 highpoly WIP.png": "File:Lilypad Islands Trunk Base 01 highpoly WIP (BZ).png",
    "File:Lilypad Islands Trunk Base 02 highpoly WIP.png": "File:Lilypad Islands Trunk Base 02 highpoly WIP (BZ).png",
    "File:Lilypad Islands Trunk Bases WIP 02.png": "File:Lilypad Islands Trunk Bases WIP 02 (BZ).png",
    "File:Lilypad creature 01 in game.jpg": "File:Lilypad creature 01 in game (BZ).jpg",
    "File:LimestoneOutcrop.png": "File:LimestoneOutcrop (BZ).png",
    "File:Lithium.png": "File:Lithium (BZ).png",
    "File:Locker.png": "File:Locker (BZ).png",
    "File:Log-128.png": "File:Log-128 (BZ).png",
    "File:Logo-uw.png": "File:Logo-uw (BZ).png",
    "File:Loldeletethisbs.png": "File:Loldeletethisbs (BZ).png",
    "File:Lost River Fish Skeleton Sketchfab.png": "File:Lost River Fish Skeleton Sketchfab (BZ).png",
    "File:Louis Karim.jpg": "File:Louis Karim (BZ).jpg",
    "File:Lstickclick.png": "File:Lstickclick (BZ).png",
    "File:Lubricant.png": "File:Lubricant (BZ).png",
    "File:MVBEncy.png": "File:MVBEncy (BZ).png",
    "File:Magnesium.png": "File:Magnesium (BZ).png",
    "File:Magnetite.png": "File:Magnetite (BZ).png",
    "File:Marblemelon-0.png": "File:Marblemelon-0 (BZ).png",
    "File:Marblemelon.png": "File:Marblemelon (BZ).png",
    "File:Marblemelon Plant Flora.png": "File:Marblemelon Plant Flora (BZ).png",
    "File:MargueritPortrait.png": "File:MargueritPortrait (BZ).png",
    "File:Markiplier Doll.png": "File:Markiplier Doll (BZ).png",
    "File:Max McGuire.jpg": "File:Max McGuire (BZ).jpg",
    "File:Medical Kit Fabricator.png": "File:Medical Kit Fabricator (BZ).png",
    "File:Men and Woman Player-Fox3D.png": "File:Men and Woman Player-Fox3D (BZ).png",
    "File:Mesmer.png": "File:Mesmer (BZ).png",
    "File:Metal Salvage.png": "File:Metal Salvage (BZ).png",
    "File:Michael Schouten.jpg": "File:Michael Schouten (BZ).jpg",
    "File:MiningSiteEntrance.jpg": "File:MiningSiteEntrance (BZ).jpg",
    "File:Miningsiteentrance.jpg": "File:Miningsiteentrance (BZ).jpg",
    "File:Mix Chips.png": "File:Mix Chips (BZ).png",
    "File:Mobile Vehicle Bay.png": "File:Mobile Vehicle Bay (BZ).png",
    "File:Mobile Vehicle Bay Fragments 1.png": "File:Mobile Vehicle Bay Fragments 1 (BZ).png",
    "File:Mobile Vehicle Bay Fragments 2.png": "File:Mobile Vehicle Bay Fragments 2 (BZ).png",
    "File:Mobile Vehicle Bay Fragments 3.png": "File:Mobile Vehicle Bay Fragments 3 (BZ).png",
    "File:Mobile Vehicle Bay Fragments 4.png": "File:Mobile Vehicle Bay Fragments 4 (BZ).png",
    "File:Mobile Vehicle Bay Fragments 5.png": "File:Mobile Vehicle Bay Fragments 5 (BZ).png",
    "File:Modification Station.png": "File:Modification Station (BZ).png",
    "File:Mohawk1.jpg": "File:Mohawk1 (BZ).jpg",
    "File:Mohawk Variants.png": "File:Mohawk Variants (BZ).png",
    "File:Mohawkplantconcept.jpg": "File:Mohawkplantconcept (BZ).jpg",
    "File:Moon Pool.png": "File:Moon Pool (BZ).png",
    "File:Moon Pool (1).png": "File:Moon Pool (1) (BZ).png",
    "File:Moon Pool (8).jpg": "File:Moon Pool (8) (BZ).jpg",
    "File:Moonpool.png": "File:Moonpool (BZ).png",
    "File:Moonpool Data Bank Image.png": "File:Moonpool Data Bank Image (BZ).png",
    "File:Moonpool Fragment 1.png": "File:Moonpool Fragment 1 (BZ).png",
    "File:Moonpool Fragment 2.png": "File:Moonpool Fragment 2 (BZ).png",
    "File:Moonpool Fragment 3.png": "File:Moonpool Fragment 3 (BZ).png",
    "File:Moonpool Fragment 4.png": "File:Moonpool Fragment 4 (BZ).png",
    "File:Moonpool Fragment 5.png": "File:Moonpool Fragment 5 (BZ).png",
    "File:Moonpool Fragment 6.png": "File:Moonpool Fragment 6 (BZ).png",
    "File:Moonpoolconceptart.jpg": "File:Moonpoolconceptart (BZ).jpg",
    "File:Moonpoolmodel2.png": "File:Moonpoolmodel2 (BZ).png",
    "File:Moonpoolmodel3.png": "File:Moonpoolmodel3 (BZ).png",
    "File:Multipurpose Room.png": "File:Multipurpose Room (BZ).png",
    "File:Narrow Bed.png": "File:Narrow Bed (BZ).png",
    "File:Nickel Ore.png": "File:Nickel Ore (BZ).png",
    "File:Nootfish Fauna.png": "File:Nootfish Fauna (BZ).png",
    "File:NuclearReactorEncy.png": "File:NuclearReactorEncy (BZ).png",
    "File:Nuclear Reactor.png": "File:Nuclear Reactor (BZ).png",
    "File:Nuclear Reactor Icon.png": "File:Nuclear Reactor Icon (BZ).png",
    "File:Nuclear Waste Disposal.png": "File:Nuclear Waste Disposal (BZ).png",
    "File:NuruFinal.png": "File:NuruFinal (BZ).png",
    "File:Nutrient Block.png": "File:Nutrient Block (BZ).png",
    "File:O2.png": "File:O2 (BZ).png",
    "File:Observatory.png": "File:Observatory (BZ).png",
    "File:Oculus.png": "File:Oculus (BZ).png",
    "File:Office Chair.png": "File:Office Chair (BZ).png",
    "File:Oliver Hobbs.jpg": "File:Oliver Hobbs (BZ).jpg",
    "File:Omega.png": "File:Omega (BZ).png",
    "File:Orange Tablet.png": "File:Orange Tablet (BZ).png",
    "File:Overgrowth (FinalRender).png": "File:Overgrowth (FinalRender) (BZ).png",
    "File:PDA.png": "File:PDA (BZ).png",
    "File:PDABlueprints.jpg": "File:PDABlueprints (BZ).jpg",
    "File:PDA Blueprints Icon.png": "File:PDA Blueprints Icon (BZ).png",
    "File:PDA Encyclopedia Icon.png": "File:PDA Encyclopedia Icon (BZ).png",
    "File:PDA Inventory Icon.png": "File:PDA Inventory Icon (BZ).png",
    "File:PDA Log.png": "File:PDA Log (BZ).png",
    "File:PDA Log Icon.png": "File:PDA Log Icon (BZ).png",
    "File:PDA Photo Manager Icon.png": "File:PDA Photo Manager Icon (BZ).png",
    "File:PDA Ping Manager Icon.png": "File:PDA Ping Manager Icon (BZ).png",
    "File:PRAWN Suit Transparent.png": "File:PRAWN Suit Transparent (BZ).png",
    "File:PS4 L1.png": "File:PS4 L1 (BZ).png",
    "File:PS4 L3.png": "File:PS4 L3 (BZ).png",
    "File:PS4 R1.png": "File:PS4 R1 (BZ).png",
    "File:PS4 R3.png": "File:PS4 R3 (BZ).png",
    "File:Pat Presley.jpg": "File:Pat Presley (BZ).jpg",
    "File:Pathfinder Tool.png": "File:Pathfinder Tool (BZ).png",
    "File:Peeper-0.png": "File:Peeper-0 (BZ).png",
    "File:Peeper.png": "File:Peeper (BZ).png",
    "File:Pengling.png": "File:Pengling (BZ).png",
    "File:Penguingo.jpg": "File:Penguingo (BZ).jpg",
    "File:Picture Frame.png": "File:Picture Frame (BZ).png",
    "File:Pingu": "File:Pingu (BZ)",
    "File:Pingu 2": "File:Pingu 2 (BZ)",
    "File:Pink Cap.png": "File:Pink Cap (BZ).png",
    "File:Pinnacarid Fauna.png": "File:Pinnacarid Fauna (BZ).png",
    "File:Pinnicarid-Alex Ries.jpg": "File:Pinnicarid-Alex Ries (BZ).jpg",
    "File:PinnicaridBody.png": "File:PinnicaridBody (BZ).png",
    "File:Pinnicarid Fauna.png": "File:Pinnicarid Fauna (BZ).png",
    "File:Pipe.png": "File:Pipe (BZ).png",
    "File:Pipe Surface Floater.png": "File:Pipe Surface Floater (BZ).png",
    "File:Plant Pot.png": "File:Plant Pot (BZ).png",
    "File:Plant Pot 2.png": "File:Plant Pot 2 (BZ).png",
    "File:Plant Pot 3.png": "File:Plant Pot 3 (BZ).png",
    "File:Plant Shelf.png": "File:Plant Shelf (BZ).png",
    "File:Plasteel Ingot.png": "File:Plasteel Ingot (BZ).png",
    "File:Plasteel Tank.png": "File:Plasteel Tank (BZ).png",
    "File:Polyaniline.png": "File:Polyaniline (BZ).png",
    "File:Poster Aurora Full.png": "File:Poster Aurora Full (BZ).png",
    "File:Poster Kitty Full.png": "File:Poster Kitty Full (BZ).png",
    "File:Potato Mix.png": "File:Potato Mix (BZ).png",
    "File:Power Cell.png": "File:Power Cell (BZ).png",
    "File:Power Cell Charger.png": "File:Power Cell Charger (BZ).png",
    "File:Power Transmitter.png": "File:Power Transmitter (BZ).png",
    "File:Power Transmitter Icon.png": "File:Power Transmitter Icon (BZ).png",
    "File:PrawnSuit1.jpg": "File:PrawnSuit1 (BZ).jpg",
    "File:PrawnSuit2.jpg": "File:PrawnSuit2 (BZ).jpg",
    "File:PrawnSuit3.jpg": "File:PrawnSuit3 (BZ).jpg",
    "File:PrawnSuit4.jpg": "File:PrawnSuit4 (BZ).jpg",
    "File:Prawn Suit.png": "File:Prawn Suit (BZ).png",
    "File:Prawn Suit Claw Arm Module.png": "File:Prawn Suit Claw Arm Module (BZ).png",
    "File:Prawn Suit Depth Module MK1.png": "File:Prawn Suit Depth Module MK1 (BZ).png",
    "File:Prawn Suit Depth Module MK2.png": "File:Prawn Suit Depth Module MK2 (BZ).png",
    "File:Prawn Suit Drill Arm.png": "File:Prawn Suit Drill Arm (BZ).png",
    "File:Prawn Suit Grappling Arm.png": "File:Prawn Suit Grappling Arm (BZ).png",
    "File:Prawn Suit Jump Jet Upgrade.png": "File:Prawn Suit Jump Jet Upgrade (BZ).png",
    "File:Prawn Suit Ping.png": "File:Prawn Suit Ping (BZ).png",
    "File:Prawn Suit Propulsion Cannon.png": "File:Prawn Suit Propulsion Cannon (BZ).png",
    "File:Prawn Suit Thermal Reactor.png": "File:Prawn Suit Thermal Reactor (BZ).png",
    "File:Prawn Suit Torpedo Arm.png": "File:Prawn Suit Torpedo Arm (BZ).png",
    "File:Prawn suit.JPG": "File:Prawn suit (BZ).JPG",
    "File:Precursor Droid-0.png": "File:Precursor Droid-0 (BZ).png",
    "File:Precursor Tether.jpeg": "File:Precursor Tether (BZ).jpeg",
    "File:Precursor tether.jpeg": "File:Precursor tether (BZ).jpeg",
    "File:Propulsion Cannon.png": "File:Propulsion Cannon (BZ).png",
    "File:Purple Brain Coral Fauna.png": "File:Purple Brain Coral Fauna (BZ).png",
    "File:Purple Tablet.png": "File:Purple Tablet (BZ).png",
    "File:Purple Tablet Fragment.png": "File:Purple Tablet Fragment (BZ).png",
    "File:Quartz.png": "File:Quartz (BZ).png",
    "File:Quilted Double Bed.png": "File:Quilted Double Bed (BZ).png",
    "File:QuoteBar.png": "File:QuoteBar (BZ).png",
    "File:RP combo 02": "File:RP combo 02 (BZ)",
    "File:RP combo 03": "File:RP combo 03 (BZ)",
    "File:RP combo 04": "File:RP combo 04 (BZ)",
    "File:RP walks 01": "File:RP walks 01 (BZ)",
    "File:RWComparison.png": "File:RWComparison (BZ).png",
    "File:Rabbit Ray-0.png": "File:Rabbit Ray-0 (BZ).png",
    "File:Rabbit Ray Fauna.png": "File:Rabbit Ray Fauna (BZ).png",
    "File:Radio.png": "File:Radio (BZ).png",
    "File:Reactor Rod.png": "File:Reactor Rod (BZ).png",
    "File:Reaper Leviathan (5).gif": "File:Reaper Leviathan (5) (BZ).gif",
    "File:Reaper Leviathan Fauna.png": "File:Reaper Leviathan Fauna (BZ).png",
    "File:Rebreather.png": "File:Rebreather (BZ).png",
    "File:Reclaimed Water.png": "File:Reclaimed Water (BZ).png",
    "File:Red Ghost Ray Fauna.png": "File:Red Ghost Ray Fauna (BZ).png",
    "File:Red Tablet.png": "File:Red Tablet (BZ).png",
    "File:Redwort-0.png": "File:Redwort-0 (BZ).png",
    "File:Redwort.png": "File:Redwort (BZ).png",
    "File:RedwortDay.jpg": "File:RedwortDay (BZ).jpg",
    "File:RedwortNight.jpg": "File:RedwortNight (BZ).jpg",
    "File:Redwort Flora.png": "File:Redwort Flora (BZ).png",
    "File:Redwort Seed.png": "File:Redwort Seed (BZ).png",
    "File:Reefback Fauna.png": "File:Reefback Fauna (BZ).png",
    "File:Reginald.png": "File:Reginald (BZ).png",
    "File:Reinforced Data.png": "File:Reinforced Data (BZ).png",
    "File:Reinforced Dive Suit.png": "File:Reinforced Dive Suit (BZ).png",
    "File:Reinforced Gloves.png": "File:Reinforced Gloves (BZ).png",
    "File:Reinforcement.png": "File:Reinforcement (BZ).png",
    "File:Repair Tool.png": "File:Repair Tool (BZ).png",
    "File:Repulsion Cannon.png": "File:Repulsion Cannon (BZ).png",
    "File:Rice Snack.png": "File:Rice Snack (BZ).png",
    "File:Rock Grub.jpg": "File:Rock Grub (BZ).jpg",
    "File:Rock Puncher Fauna.png": "File:Rock Puncher Fauna (BZ).png",
    "File:Rock puncher": "File:Rock puncher (BZ)",
    "File:Rock puncher vs human2.jpg": "File:Rock puncher vs human2 (BZ).jpg",
    "File:RockgrubA.jpg": "File:RockgrubA (BZ).jpg",
    "File:RockgrubB.jpg": "File:RockgrubB (BZ).jpg",
    "File:RockgrubC.jpg": "File:RockgrubC (BZ).jpg",
    "File:RockgrubNight.jpg": "File:RockgrubNight (BZ).jpg",
    "File:Rockgrub Fauna.png": "File:Rockgrub Fauna (BZ).png",
    "File:Rockgrub Size.jpg": "File:Rockgrub Size (BZ).jpg",
    "File:Rockgrub concept art.jpg": "File:Rockgrub concept art (BZ).jpg",
    "File:Room.png": "File:Room (BZ).png",
    "File:Ruby.png": "File:Ruby (BZ).png",
    "File:SNBZ.jpg": "File:SNBZ (BZ).jpg",
    "File:SUBNAUTICA BELOW ZERO.png": "File:SUBNAUTICA BELOW ZERO (BZ).png",
    "File:Salt Deposit.png": "File:Salt Deposit (BZ).png",
    "File:Sand Shark.png": "File:Sand Shark (BZ).png",
    "File:Scanner.png": "File:Scanner (BZ).png",
    "File:Scanner Room.png": "File:Scanner Room (BZ).png",
    "File:Scanner Room HUD Chip.png": "File:Scanner Room HUD Chip (BZ).png",
    "File:Scanner Room Range Upgrade.png": "File:Scanner Room Range Upgrade (BZ).png",
    "File:Scanner Room Speed Upgrade.png": "File:Scanner Room Speed Upgrade (BZ).png",
    "File:Scott MacDonald.jpg": "File:Scott MacDonald (BZ).jpg",
    "File:Scott Thunelius.jpg": "File:Scott Thunelius (BZ).jpg",
    "File:Screen Shot 2018-09-06 at 1.29.15 PM.png": "File:Screen Shot 2018-09-06 at 1.29.15 PM (BZ).png",
    "File:Screenshot.jpg": "File:Screenshot (BZ).jpg",
    "File:Screenshot (1).png": "File:Screenshot (1) (BZ).png",
    "File:Screenshot (10).png": "File:Screenshot (10) (BZ).png",
    "File:Screenshot (13).png": "File:Screenshot (13) (BZ).png",
    "File:Screenshot (15).png": "File:Screenshot (15) (BZ).png",
    "File:Screenshot (2).png": "File:Screenshot (2) (BZ).png",
    "File:Screenshot (3).png": "File:Screenshot (3) (BZ).png",
    "File:Screenshot (4).png": "File:Screenshot (4) (BZ).png",
    "File:Screenshot (8).png": "File:Screenshot (8) (BZ).png",
    "File:Screenshot (9).png": "File:Screenshot (9) (BZ).png",
    "File:Screenshot 1.png": "File:Screenshot 1 (BZ).png",
    "File:SeaEmperor9.jpg": "File:SeaEmperor9 (BZ).jpg",
    "File:SeaEmperorB.jpg": "File:SeaEmperorB (BZ).jpg",
    "File:SeaEmperorD.jpg": "File:SeaEmperorD (BZ).jpg",
    "File:Sea Dragon Leviathan Fauna.png": "File:Sea Dragon Leviathan Fauna (BZ).png",
    "File:Sea Emperor (Black)-0.jpg": "File:Sea Emperor (Black)-0 (BZ).jpg",
    "File:Sea Emperor (Black)-1.jpg": "File:Sea Emperor (Black)-1 (BZ).jpg",
    "File:Sea Emperor (Front-Black).jpg": "File:Sea Emperor (Front-Black) (BZ).jpg",
    "File:Sea Emperor Leviathan Fauna.png": "File:Sea Emperor Leviathan Fauna (BZ).png",
    "File:Sea Emperor Leviathan Fauna (Juvenile).png": "File:Sea Emperor Leviathan Fauna (Juvenile) (BZ).png",
    "File:Sea Monkey Fauna.png": "File:Sea Monkey Fauna (BZ).png",
    "File:Sea Monkey Fauna Baby.png": "File:Sea Monkey Fauna Baby (BZ).png",
    "File:Sea Treader Fauna.png": "File:Sea Treader Fauna (BZ).png",
    "File:Sea Truck Interior.png": "File:Sea Truck Interior (BZ).png",
    "File:Sea emperor.jpg": "File:Sea emperor (BZ).jpg",
    "File:Sea truck interior.png": "File:Sea truck interior (BZ).png",
    "File:Seadragon.jpg": "File:Seadragon (BZ).jpg",
    "File:Seaglide.png": "File:Seaglide (BZ).png",
    "File:Seamoth 2.gif": "File:Seamoth 2 (BZ).gif",
    "File:Seamoth Gas Torpedo.png": "File:Seamoth Gas Torpedo (BZ).png",
    "File:Seamoth Hull Reinforcement.png": "File:Seamoth Hull Reinforcement (BZ).png",
    "File:Seamoth Vortex Torpedo.png": "File:Seamoth Vortex Torpedo (BZ).png",
    "File:Sergey Solovyev.jpg": "File:Sergey Solovyev (BZ).jpg",
    "File:Shard 01.jpg": "File:Shard 01 (BZ).jpg",
    "File:Shoal of Fish Fauna.png": "File:Shoal of Fish Fauna (BZ).png",
    "File:Shocker Fauna.png": "File:Shocker Fauna (BZ).png",
    "File:Sign.png": "File:Sign (BZ).png",
    "File:Silicone Rubber.png": "File:Silicone Rubber (BZ).png",
    "File:Silver Ore.png": "File:Silver Ore (BZ).png",
    "File:Single Bed.png": "File:Single Bed (BZ).png",
    "File:Single Wall Shelf.png": "File:Single Wall Shelf (BZ).png",
    "File:Site-logo.png": "File:Site-logo (BZ).png",
    "File:SkyRay.jpg": "File:SkyRay (BZ).jpg",
    "File:Skyray.png": "File:Skyray (BZ).png",
    "File:Skyray2.jpg": "File:Skyray2 (BZ).jpg",
    "File:SkyrayA.jpg": "File:SkyrayA (BZ).jpg",
    "File:SkyrayB.jpg": "File:SkyrayB (BZ).jpg",
    "File:Skyray Fauna.png": "File:Skyray Fauna (BZ).png",
    "File:Skyray and Large Bird.jpeg": "File:Skyray and Large Bird (BZ).jpeg",
    "File:Small Marblemelon.png": "File:Small Marblemelon (BZ).png",
    "File:Small sample flask.png": "File:Small sample flask (BZ).png",
    "File:Snack1.png": "File:Snack1 (BZ).png",
    "File:Snack2.png": "File:Snack2 (BZ).png",
    "File:Snack3.png": "File:Snack3 (BZ).png",
    "File:Snake Mushroom Model.png": "File:Snake Mushroom Model (BZ).png",
    "File:Snake Mushroom Spore.png": "File:Snake Mushroom Spore (BZ).png",
    "File:Snowstalker Fauna.png": "File:Snowstalker Fauna (BZ).png",
    "File:SolarPanelEncy.png": "File:SolarPanelEncy (BZ).png",
    "File:Solar Panel.png": "File:Solar Panel (BZ).png",
    "File:Solar Panel Icon.png": "File:Solar Panel Icon (BZ).png",
    "File:Spadefish Fauna.png": "File:Spadefish Fauna (BZ).png",
    "File:Speckled Rattler.png": "File:Speckled Rattler (BZ).png",
    "File:Speckled Rattler Flora.png": "File:Speckled Rattler Flora (BZ).png",
    "File:Spike Trap (1).jpg": "File:Spike Trap (1) (BZ).jpg",
    "File:Spike Trap (2).jpg": "File:Spike Trap (2) (BZ).jpg",
    "File:Spike Trap Concept Art.jpg": "File:Spike Trap Concept Art (BZ).jpg",
    "File:Spike Trap Flora.png": "File:Spike Trap Flora (BZ).png",
    "File:Spiketrapmodel.png": "File:Spiketrapmodel (BZ).png",
    "File:SpineFish.jpg": "File:SpineFish (BZ).jpg",
    "File:Spine Eel Fauna.png": "File:Spine Eel Fauna (BZ).png",
    "File:Spinefish.jpg": "File:Spinefish (BZ).jpg",
    "File:Spinefish.png": "File:Spinefish (BZ).png",
    "File:SpinefishA.jpg": "File:SpinefishA (BZ).jpg",
    "File:SpinefishB.jpg": "File:SpinefishB (BZ).jpg",
    "File:SpinefishC.jpg": "File:SpinefishC (BZ).jpg",
    "File:SpinefishConceptArt.JPG": "File:SpinefishConceptArt (BZ).JPG",
    "File:SpinefishD.jpg": "File:SpinefishD (BZ).jpg",
    "File:Spinefish Fauna.png": "File:Spinefish Fauna (BZ).png",
    "File:Spinnerfish.png": "File:Spinnerfish (BZ).png",
    "File:Spoiler.png": "File:Spoiler (BZ).png",
    "File:Spore Sack.png": "File:Spore Sack (BZ).png",
    "File:Spore Sack Seed.png": "File:Spore Sack Seed (BZ).png",
    "File:Spotlight.png": "File:Spotlight (BZ).png",
    "File:Spotted Dockleaf.png": "File:Spotted Dockleaf (BZ).png",
    "File:Spotted Dockleaf Data Bank Image.png": "File:Spotted Dockleaf Data Bank Image (BZ).png",
    "File:Spotted Dockleaf Flora.png": "File:Spotted Dockleaf Flora (BZ).png",
    "File:Spotted Dockleaf Seed.png": "File:Spotted Dockleaf Seed (BZ).png",
    "File:Spotted Reeds Flora.png": "File:Spotted Reeds Flora (BZ).png",
    "File:SquidShark 06.jpg": "File:SquidShark 06 (BZ).jpg",
    "File:Stalker-1.png": "File:Stalker-1 (BZ).png",
    "File:Stalker Fauna.png": "File:Stalker Fauna (BZ).png",
    "File:Stalker Tooth.png": "File:Stalker Tooth (BZ).png",
    "File:Standard O₂ Tank.png": "File:Standard O₂ Tank (BZ).png",
    "File:Starship Souvenir.png": "File:Starship Souvenir (BZ).png",
    "File:Stasis Rifle.png": "File:Stasis Rifle (BZ).png",
    "File:Stickclick.png": "File:Stickclick (BZ).png",
    "File:Stillsuit.png": "File:Stillsuit (BZ).png",
    "File:Stop.png": "File:Stop (BZ).png",
    "File:Storage Module.png": "File:Storage Module (BZ).png",
    "File:StylizedSpringtrap(Watermark).png": "File:StylizedSpringtrap(Watermark) (BZ).png",
    "File:Subnautica.jpg": "File:Subnautica (BZ).jpg",
    "File:Subnautica BZ Glitch.png": "File:Subnautica BZ Glitch (BZ).png",
    "File:Subnautica Below Zero.png": "File:Subnautica Below Zero (BZ).png",
    "File:Subnautica Below Zero Arctic Living Update": "File:Subnautica Below Zero Arctic Living Update (BZ)",
    "File:Subnautica Below Zero Early Access Trailer": "File:Subnautica Below Zero Early Access Trailer (BZ)",
    "File:Subnautica Below Zero Seatruck Update": "File:Subnautica Below Zero Seatruck Update (BZ)",
    "File:Subnautica Below Zero Snowfox Update": "File:Subnautica Below Zero Snowfox Update (BZ)",
    "File:Subnautica Below Zero Spy Pengling Update": "File:Subnautica Below Zero Spy Pengling Update (BZ)",
    "File:Subnautica Character.jpg": "File:Subnautica Character (BZ).jpg",
    "File:Subnautica bz glitch.png": "File:Subnautica bz glitch (BZ).png",
    "File:Subnautica map.jpg": "File:Subnautica map (BZ).jpg",
    "File:Sulfur Plant.png": "File:Sulfur Plant (BZ).png",
    "File:Sulfur Plant Flora.png": "File:Sulfur Plant Flora (BZ).png",
    "File:Sunbeam Log.png": "File:Sunbeam Log (BZ).png",
    "File:SunkenSunset2.png": "File:SunkenSunset2 (BZ).png",
    "File:Surface foilage 4.jpg": "File:Surface foilage 4 (BZ).jpg",
    "File:Survival Knife.png": "File:Survival Knife (BZ).png",
    "File:Survivor Log Long.png": "File:Survivor Log Long (BZ).png",
    "File:Swim Charge Fins.png": "File:Swim Charge Fins (BZ).png",
    "File:SwitchA.png": "File:SwitchA (BZ).png",
    "File:SwitchB.png": "File:SwitchB (BZ).png",
    "File:SwitchDownbutton.png": "File:SwitchDownbutton (BZ).png",
    "File:SwitchL.png": "File:SwitchL (BZ).png",
    "File:SwitchLeftbutton.png": "File:SwitchLeftbutton (BZ).png",
    "File:SwitchMinus.png": "File:SwitchMinus (BZ).png",
    "File:SwitchPlus.png": "File:SwitchPlus (BZ).png",
    "File:SwitchR.png": "File:SwitchR (BZ).png",
    "File:SwitchRightbutton.png": "File:SwitchRightbutton (BZ).png",
    "File:SwitchSl.png": "File:SwitchSl (BZ).png",
    "File:SwitchSr.png": "File:SwitchSr (BZ).png",
    "File:SwitchUpbutton.png": "File:SwitchUpbutton (BZ).png",
    "File:SwitchX.png": "File:SwitchX (BZ).png",
    "File:SwitchY.png": "File:SwitchY (BZ).png",
    "File:SwitchZl.png": "File:SwitchZl (BZ).png",
    "File:SwitchZr.png": "File:SwitchZr (BZ).png",
    "File:Swivel Chair.png": "File:Swivel Chair (BZ).png",
    "File:Sylvain Hel.jpg": "File:Sylvain Hel (BZ).jpg",
    "File:Symbiote Fauna.png": "File:Symbiote Fauna (BZ).png",
    "File:Synthetic Fibers.png": "File:Synthetic Fibers (BZ).png",
    "File:T Compartment.png": "File:T Compartment (BZ).png",
    "File:T Corridor.png": "File:T Corridor (BZ).png",
    "File:Table Coral Sample.png": "File:Table Coral Sample (BZ).png",
    "File:Tenor.gif": "File:Tenor (BZ).gif",
    "File:Terminal Concept.jpg": "File:Terminal Concept (BZ).jpg",
    "File:Test.png": "File:Test (BZ).png",
    "File:TestQuoteIcon.png": "File:TestQuoteIcon (BZ).png",
    "File:Thangtingytiantipnesa.png": "File:Thangtingytiantipnesa (BZ).png",
    "File:TheDegasi.png": "File:TheDegasi (BZ).png",
    "File:TheInkDemon(FinalRender).png": "File:TheInkDemon(FinalRender) (BZ).png",
    "File:Thermal Plant.png": "File:Thermal Plant (BZ).png",
    "File:Thermal Plant Fragment 1.png": "File:Thermal Plant Fragment 1 (BZ).png",
    "File:Thermal Plant Fragment 2.png": "File:Thermal Plant Fragment 2 (BZ).png",
    "File:Thermal Plant Fragment 3.png": "File:Thermal Plant Fragment 3 (BZ).png",
    "File:Thermal Plant Icon.png": "File:Thermal Plant Icon (BZ).png",
    "File:Thermal Zone WIp05a.jpg": "File:Thermal Zone WIp05a (BZ).jpg",
    "File:Thermoblade.png": "File:Thermoblade (BZ).png",
    "File:TigerPlantConceptArt2.jpg": "File:TigerPlantConceptArt2 (BZ).jpg",
    "File:Titan.png": "File:Titan (BZ).png",
    "File:Titan Holefish Fauna.png": "File:Titan Holefish Fauna (BZ).png",
    "File:Titanium.png": "File:Titanium (BZ).png",
    "File:Titanium Ingot.png": "File:Titanium Ingot (BZ).png",
    "File:Tom Jubert.jpg": "File:Tom Jubert (BZ).jpg",
    "File:Toy Car.png": "File:Toy Car (BZ).png",
    "File:Transfuser.png": "File:Transfuser (BZ).png",
    "File:Trash Can.png": "File:Trash Can (BZ).png",
    "File:Trash Cans.png": "File:Trash Cans (BZ).png",
    "File:Triops Fauna.png": "File:Triops Fauna (BZ).png",
    "File:Trivalve Fauna.png": "File:Trivalve Fauna (BZ).png",
    "File:Trunk Base + 01, 02, 03, 04 tiled sections.png": "File:Trunk Base + 01, 02, 03, 04 tiled sections (BZ).png",
    "File:Trunk Base + 01, 02 tiled sections.png": "File:Trunk Base + 01, 02 tiled sections (BZ).png",
    "File:Twist bridges 1.jpg": "File:Twist bridges 1 (BZ).jpg",
    "File:TwistyBridges01.jpg": "File:TwistyBridges01 (BZ).jpg",
    "File:Twisty bridges 01 detailed.jpg": "File:Twisty bridges 01 detailed (BZ).jpg",
    "File:Ultra Glide Fins.png": "File:Ultra Glide Fins (BZ).png",
    "File:Ultra High Capacity Tank.png": "File:Ultra High Capacity Tank (BZ).png",
    "File:Unknown.png": "File:Unknown (BZ).png",
    "File:Unknown (1).png": "File:Unknown (1) (BZ).png",
    "File:Unspecified.jpg": "File:Unspecified (BZ).jpg",
    "File:Untitled.png": "File:Untitled (BZ).png",
    "File:Uparrow.png": "File:Uparrow (BZ).png",
    "File:Uraninite Crystal.png": "File:Uraninite Crystal (BZ).png",
    "File:Uranium.png": "File:Uranium (BZ).png",
    "File:VBComparison.png": "File:VBComparison (BZ).png",
    "File:Vac-pack Infobox.png": "File:Vac-pack Infobox (BZ).png",
    "File:Vehicle Upgrade Console.png": "File:Vehicle Upgrade Console (BZ).png",
    "File:Vehicle Upgrade Console PDA Encyclopedia.png": "File:Vehicle Upgrade Console PDA Encyclopedia (BZ).png",
    "File:Vending Machine.png": "File:Vending Machine (BZ).png",
    "File:Vertical Connector.png": "File:Vertical Connector (BZ).png",
    "File:VioletBeauregardeDay.jpg": "File:VioletBeauregardeDay (BZ).jpg",
    "File:VioletBeauregardeNight.jpg": "File:VioletBeauregardeNight (BZ).jpg",
    "File:Violet Beau.png": "File:Violet Beau (BZ).png",
    "File:Violet Beau Flora.png": "File:Violet Beau Flora (BZ).png",
    "File:Violet Beau Seed.png": "File:Violet Beau Seed (BZ).png",
    "File:Voxel Shrub Flora.png": "File:Voxel Shrub Flora (BZ).png",
    "File:Vyacheslav Sedovich.png": "File:Vyacheslav Sedovich (BZ).png",
    "File:Wall Locker.png": "File:Wall Locker (BZ).png",
    "File:Wall Planter.png": "File:Wall Planter (BZ).png",
    "File:Wall Shelves.png": "File:Wall Shelves (BZ).png",
    "File:Warper Fauna.png": "File:Warper Fauna (BZ).png",
    "File:Water.png": "File:Water (BZ).png",
    "File:Water Filtration Machine.png": "File:Water Filtration Machine (BZ).png",
    "File:Waterproof Locker.png": "File:Waterproof Locker (BZ).png",
    "File:White Tablet.png": "File:White Tablet (BZ).png",
    "File:Wiki-background": "File:Wiki-background (BZ)",
    "File:Wiki-wordmark.png": "File:Wiki-wordmark (BZ).png",
    "File:Window.png": "File:Window (BZ).png",
    "File:Wiring Kit.png": "File:Wiring Kit (BZ).png",
    "File:Workbench Blueprint.png": "File:Workbench Blueprint (BZ).png",
    "File:Wrecked.png": "File:Wrecked (BZ).png",
    "File:Writhing Weed Flora.png": "File:Writhing Weed Flora (BZ).png",
    "File:X Compartment.png": "File:X Compartment (BZ).png",
    "File:X Corridor.png": "File:X Corridor (BZ).png",
    "File:Xbox a.png": "File:Xbox a (BZ).png",
    "File:Xbox b.png": "File:Xbox b (BZ).png",
    "File:Xbox back.png": "File:Xbox back (BZ).png",
    "File:Xbox dpad.png": "File:Xbox dpad (BZ).png",
    "File:Xbox dpad down.png": "File:Xbox dpad down (BZ).png",
    "File:Xbox dpad left.png": "File:Xbox dpad left (BZ).png",
    "File:Xbox dpad right.png": "File:Xbox dpad right (BZ).png",
    "File:Xbox dpad up.png": "File:Xbox dpad up (BZ).png",
    "File:Xbox left bumper.png": "File:Xbox left bumper (BZ).png",
    "File:Xbox left stick.png": "File:Xbox left stick (BZ).png",
    "File:Xbox left trigger.png": "File:Xbox left trigger (BZ).png",
    "File:Xbox right bumper.png": "File:Xbox right bumper (BZ).png",
    "File:Xbox right stick.png": "File:Xbox right stick (BZ).png",
    "File:Xbox right trigger.png": "File:Xbox right trigger (BZ).png",
    "File:Xbox start.png": "File:Xbox start (BZ).png",
    "File:Xbox x.png": "File:Xbox x (BZ).png",
    "File:Xbox y.png": "File:Xbox y (BZ).png",
    "File:ZoeyConstellaFinal.png": "File:ZoeyConstellaFinal (BZ).png",
}

# make a copy object that contains all of the elements of pages, templates, and files, instead of changing
# any one of these objects in place
to_move = {}
to_move.update(pages)
to_move.update(templates)
to_move.update(files)


def move_pages():
    startat_page = 'File:Arctic Peeper Fauna.png'
    passed_startat = False
    for source, dest in to_move.items():
        if source == startat_page:
            passed_startat = True
        if not passed_startat:
            continue
        source_page = site.client.pages[source]
        if source_page.exists:
            text = source_page.text()
            if 'redirect' in text.lower():
                print("omg it's a redirect! {}".format(source))
                continue
            # site.move(source_page, dest, no_redirect=True, reason=summary)


class PageModifier(PageModifierBase):
    def update_plaintext(self, text):
        # We're assuming there's no underscores in any page or file or template name in the entire wiki
        
        # embedded files - File: is already part of the page name
        for source, dest in files.items():
            text = text.replace('[[{}'.format(source), '[[{}'.format(dest))
        # links to files
        for source, dest in files.items():
            text = text.replace('[[:{}'.format(source), '[[:{}'.format(dest))
        
        # links to pages (no display text)
        for source, dest in pages.items():
            text = text.replace('[[{}]]'.format(source), '[[{}|{}]]'.format(dest, source))
        # links to pages (display text)
        for source, dest in pages.items():
            text = text.replace('[[{}|'.format(source), '[[{}|'.format(dest))
        # links to pages (display text with pipes)
        for source, dest in pages.items():
            text = text.replace('[[{}{{{{!}}}}'.format(source), '[[{}{{{{!}}}}'.format(dest))
        return text
    
    def update_wikitext(self, wikitext):
        
        infoboxes = ['Flora', 'Fauna', 'Biome', 'Craftable']
        infoboxes_copy = copy(infoboxes)
        for infobox in infoboxes:
            infoboxes_copy.append(infobox + ' (BZ)')
        infoboxes = copy(infoboxes_copy)
        for infobox in infoboxes_copy:
            infoboxes.append('Template:' + infobox)
        
        for template in wikitext.filter_templates():
            template: Template
            template_name = template.name
            
            # case of replacing images in infobox
            if any([template_name.matches(x) for x in infoboxes]):
                self.update_image(template, 'image1')
                self.update_image(template, 'image2')
                self.update_image(template, 'image3')
            
            if any([template_name.matches(x) for x in
                    ['Recipe2', 'Template:Recipe2', 'Recipe2 (BZ)', 'Template:Recipe2 (BZ)']]):
                self.update_page(template, 1)
                self.update_page(template, 'page')
            
            # case of replacing embedded templates
            for source, dest in templates.items():
                if template_name.matches(source) or template_name.matches(source.replace('Template:', '')):
                    template.name = dest.replace('Template:', '')
        
        # case of updating galleries
        for tag in wikitext.filter_tags():
            tag: Tag
            if not tag.tag == 'gallery':
                continue
            contents = str(tag.contents)
            lines = contents.split('\n')
            for i, line in enumerate(lines):
                # let's not randomly add File: if we're not *actually* updating a file link here ok
                matched = False
                please_remove_file = False
                if not line.startswith('File:'):
                    please_remove_file = True
                    line = 'File:' + line
                for source, dest in files.items():
                    if line.startswith(source):
                        if please_remove_file:
                            dest = dest.replace('File:', '')
                        line = line.replace(source, dest)
                        matched = True
                if matched:
                    lines[i] = line
            tag.contents = '\n'.join(lines)
    
    @staticmethod
    def update_image(template, param_name):
        if not template.has(param_name):
            return
        cur_value = template.get(param_name).value.strip()
        for source, dest in files.items():
            # they could've put either File:Filename or just Filename as the param value
            if cur_value == source:
                template.add(param_name, dest)
                return
            # we'll break up the cases so we do minimal disruption
            if cur_value == source.replace('File:', ''):
                template.add(param_name, dest.replace('File:', ''))
                return
    
    @staticmethod
    def update_page(template, param_name):
        if not template.has(param_name):
            return
        cur_value = template.get(param_name).value.strip()
        for source, dest in pages.items():
            if cur_value == source:
                template.add(param_name, dest)
                return


if __name__ == '__main__':
    # PageModifier(site, page_list=site.client.allpages(),
    #              summary=summary).run()
    move_pages()
